language: python
python:
    - 3.5
    - 3.4
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
sudo: false
install:
    - pip install .
    - pip install traitlets[test] pytest-cov codecov
script:
    - py.test --cov traitlets -v traitlets
after_success:
    - codecov
